apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-deployment-gateway
  labels:
    app: service-gateway
spec:
  replicas: 1
  selector:
    matchLabels:
      app: service-gateway
  template:
    metadata:
      labels:
        app: service-gateway
    spec:
      containers:
        - name: app-gateway
          image: juliocm18/app-gateway
          ports:
            - containerPort: 10000
